name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger workflow when code is pushed to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Checks out your repository code

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Use the Node.js version specified here

      - name: Install dependencies
        run: npm install # Install project dependencies

      - name: Build the project
        run: npm run build # Build the project into static files

      - name: Deploy to GitHub Pages
        run: npm run deploy # Deploy the static files to GitHub Pages
